"""
scaffold_project tool — deterministic MLOps project generator.

Creates a complete, runnable MLOps repo skeleton (data prep, training with
MLflow tracking, evaluation, FastAPI serving, tests, Docker) with TODO
markers for the LLM to fill in stage by stage. No LLM is involved in the
scaffold itself, so structure quality is independent of model size — a small
local model only has to complete marked sections one file at a time.

Also writes plan.json: a stage state file with a verification gate command
per stage. The agent works one stage at a time, runs the gate, and only
advances when it passes.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

DEFAULT_PARENT_DIR = "C:/Users/bbuse/Desktop"

_DOMAIN_DEPS = {
    "tabular": ["pandas", "scikit-learn", "lightgbm", "xgboost", "shap"],
    "cv": ["torch", "torchvision", "timm", "pillow"],
    "nlp": ["torch", "transformers", "datasets", "accelerate"],
    "timeseries": ["pandas", "scikit-learn", "lightgbm", "statsmodels"],
    "rl": ["gymnasium", "stable-baselines3"],
}

_CORE_DEPS = ["mlflow", "fastapi", "uvicorn", "pydantic", "joblib", "pyarrow"]
_DEV_DEPS = ["pytest", "httpx", "ruff", "mypy"]

_DOMAIN_HINTS = {
    "tabular": "Start with LightGBM. StratifiedKFold(5) for classification. No scaling needed for tree models.",
    "cv": "Small dataset: EfficientNet-B0 pretrained. model.eval() + torch.no_grad() in validation. Save best checkpoint, not last.",
    "nlp": "distilbert for CPU, roberta-base for accuracy. LR 2e-5 to 5e-5, 3-5 epochs. Macro-F1 on imbalanced data.",
    "timeseries": "ALWAYS time-based split, never random. Lag features shift >= 1. MAE + RMSE, avoid MAPE with zeros.",
    "rl": "PPO first. Vectorised envs (8+). EvalCallback to save best model. Save VecNormalize stats with the model.",
}


def _slugify(name: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9_-]+", "-", name.strip().lower()).strip("-")
    return slug or "ml-project"


def _pyproject(project: str, domain: str) -> str:
    deps = sorted(set(_CORE_DEPS + _DOMAIN_DEPS[domain]))
    deps_str = ",\n".join(f'    "{d}"' for d in deps)
    dev_str = ",\n".join(f'    "{d}"' for d in _DEV_DEPS)
    return f'''[project]
name = "{project}"
version = "0.1.0"
description = "End-to-end MLOps project ({domain})"
requires-python = ">=3.11"
dependencies = [
{deps_str},
]

[dependency-groups]
dev = [
{dev_str},
]

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
check_untyped_defs = true
'''


def _gitignore() -> str:
    return """__pycache__/
*.pyc
.venv/
mlruns/
mlartifacts/
models/*.pkl
models/*.pt
data/raw/
data/processed/
.pytest_cache/
.mypy_cache/
.ruff_cache/
"""


def _readme(project: str, domain: str, task: str) -> str:
    return f"""# {project}

{task or f"End-to-end {domain} ML project."}

Generated by ML Agent's `scaffold_project` — fill in the `# TODO(agent)` sections
stage by stage (see `plan.json` for the current stage and its verification gate).

## Pipeline

```
uv sync                                       # install dependencies
uv run python -m src.data_prep               # stage: data_prep
uv run python -m src.train                   # stage: train (logs to MLflow)
uv run python -m src.evaluate                # stage: evaluate
uv run pytest -q                             # stage: test
uv run uvicorn src.serve:app --port 8000     # stage: serve
```

## MLflow tracking

Runs are logged to the local `mlruns/` directory. To browse:

```
uv run mlflow ui --port 5000
```

## Serving

`src/serve.py` exposes `POST /predict` and `GET /health`. Build the Docker image:

```
docker build -t {project} .
docker run -p 8000:8000 {project}
```
"""


def _plan(domain: str, task: str) -> dict:
    return {
        "project_task": task or f"{domain} ML project",
        "domain": domain,
        "current_stage": "data_prep",
        "stages": [
            {
                "name": "data_prep",
                "file": "src/data_prep.py",
                "goal": "Load raw data, clean it, engineer features, write data/processed/dataset.parquet",
                "gate": "uv run python -m src.data_prep",
                "status": "pending",
            },
            {
                "name": "train",
                "file": "src/train.py",
                "goal": "Train the model on processed data, log params+metrics to MLflow, save models/model.pkl",
                "gate": "uv run python -m src.train --smoke-test",
                "status": "pending",
            },
            {
                "name": "evaluate",
                "file": "src/evaluate.py",
                "goal": "Evaluate saved model on held-out data, log metrics to MLflow, print a metrics report",
                "gate": "uv run python -m src.evaluate",
                "status": "pending",
            },
            {
                "name": "test",
                "file": "tests/test_pipeline.py",
                "goal": "Make the smoke tests pass end-to-end",
                "gate": "uv run pytest -q",
                "status": "pending",
            },
            {
                "name": "serve",
                "file": "src/serve.py",
                "goal": "Complete the /predict endpoint so it returns real model predictions",
                "gate": "uv run pytest -q tests/test_pipeline.py::test_serve_predict",
                "status": "pending",
            },
        ],
        "notes": {},
    }


def _config_py(domain: str) -> str:
    return f'''"""Shared configuration for the pipeline."""

from dataclasses import dataclass, field
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
MODELS_DIR = PROJECT_ROOT / "models"
PROCESSED_DATA = DATA_DIR / "processed" / "dataset.parquet"
MODEL_PATH = MODELS_DIR / "model.pkl"

MLFLOW_EXPERIMENT = "{domain}-pipeline"


@dataclass
class TrainConfig:
    """Training hyperparameters. Tune here, not inline in train.py."""

    random_seed: int = 42
    test_size: float = 0.2
    # TODO(agent): add model hyperparameters for this task
    model_params: dict = field(default_factory=dict)
'''


def _data_prep_py(domain: str, task: str) -> str:
    hint = _DOMAIN_HINTS[domain]
    return f'''"""Stage 1: data preparation.

Task: {task or f"{domain} project"}
Domain notes: {hint}

Run: uv run python -m src.data_prep
"""

import logging

import pandas as pd

from src.config import DATA_DIR, PROCESSED_DATA

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger(__name__)


def load_raw_data() -> pd.DataFrame:
    """Load the raw dataset.

    TODO(agent): implement — load from data/raw/, a URL, or a library dataset.
    Document the source in a comment. Do NOT invent columns: inspect the real
    data first if unsure.
    """
    raise NotImplementedError("TODO(agent): implement load_raw_data")


def build_features(df: pd.DataFrame) -> pd.DataFrame:
    """Clean the data and engineer features.

    TODO(agent): implement — handle missing values, encode categoricals,
    engineer features appropriate to the task. Keep the target column intact.
    """
    raise NotImplementedError("TODO(agent): implement build_features")


def main() -> None:
    df = load_raw_data()
    logger.info("Loaded raw data: %s rows, %s cols", *df.shape)
    df = build_features(df)
    PROCESSED_DATA.parent.mkdir(parents=True, exist_ok=True)
    df.to_parquet(PROCESSED_DATA, index=False)
    logger.info("Wrote %s (%s rows, %s cols)", PROCESSED_DATA, *df.shape)


if __name__ == "__main__":
    main()
'''


def _train_py(domain: str) -> str:
    hint = _DOMAIN_HINTS[domain]
    return f'''"""Stage 2: model training with MLflow tracking.

Domain notes: {hint}

Run: uv run python -m src.train              (full run)
     uv run python -m src.train --smoke-test (fast gate: small sample, 1 iteration)
"""

import argparse
import logging

import joblib
import mlflow
import pandas as pd

from src.config import MLFLOW_EXPERIMENT, MODEL_PATH, PROCESSED_DATA, TrainConfig

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger(__name__)


def train(config: TrainConfig, smoke_test: bool = False) -> dict[str, float]:
    """Train the model and return validation metrics.

    TODO(agent): implement —
    1. Load PROCESSED_DATA, split features/target (time-based split for timeseries!)
    2. If smoke_test: subsample to <= 200 rows / 1 boosting round / 1 epoch so it
       finishes in seconds — this is the verification gate
    3. Train the model, compute validation metrics
    4. Save the fitted model with joblib.dump(model, MODEL_PATH)
    5. Return a dict of metric name -> value
    """
    raise NotImplementedError("TODO(agent): implement train")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--smoke-test", action="store_true", help="Tiny fast run for the stage gate")
    args = parser.parse_args()

    config = TrainConfig()
    mlflow.set_experiment(MLFLOW_EXPERIMENT)
    with mlflow.start_run(run_name="smoke" if args.smoke_test else "train"):
        mlflow.log_params({{"smoke_test": args.smoke_test, **config.model_params}})
        MODEL_PATH.parent.mkdir(parents=True, exist_ok=True)
        metrics = train(config, smoke_test=args.smoke_test)
        mlflow.log_metrics(metrics)
        logger.info("Metrics: %s", metrics)
        logger.info("Model saved to %s", MODEL_PATH)


if __name__ == "__main__":
    main()
'''


def _evaluate_py() -> str:
    return '''"""Stage 3: evaluation of the saved model.

Run: uv run python -m src.evaluate
"""

import logging

import joblib
import mlflow
import pandas as pd

from src.config import MLFLOW_EXPERIMENT, MODEL_PATH, PROCESSED_DATA

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger(__name__)


def evaluate() -> dict[str, float]:
    """Evaluate the saved model on held-out data.

    TODO(agent): implement —
    1. Load the model from MODEL_PATH and data from PROCESSED_DATA
    2. Recreate the same held-out split used in training (same seed/config)
    3. Compute task-appropriate metrics (and a confusion matrix / residual
       summary where it applies)
    4. Return a dict of metric name -> value
    """
    raise NotImplementedError("TODO(agent): implement evaluate")


def main() -> None:
    mlflow.set_experiment(MLFLOW_EXPERIMENT)
    with mlflow.start_run(run_name="evaluate"):
        metrics = evaluate()
        mlflow.log_metrics(metrics)
        for name, value in metrics.items():
            logger.info("%s: %.4f", name, value)


if __name__ == "__main__":
    main()
'''


def _serve_py(project: str) -> str:
    return f'''"""Stage 5: FastAPI model serving.

Run: uv run uvicorn src.serve:app --port 8000
"""

import logging
from contextlib import asynccontextmanager

import joblib
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

from src.config import MODEL_PATH

logger = logging.getLogger(__name__)
_state: dict = {{}}


@asynccontextmanager
async def lifespan(app: FastAPI):
    if MODEL_PATH.exists():
        _state["model"] = joblib.load(MODEL_PATH)
        logger.info("Loaded model from %s", MODEL_PATH)
    else:
        logger.warning("No model at %s — /predict will return 503", MODEL_PATH)
    yield
    _state.clear()


app = FastAPI(title="{project}", lifespan=lifespan)


class PredictRequest(BaseModel):
    """TODO(agent): replace with the real feature fields for this model,
    matching the columns train.py was fitted on. Example:

    age: float
    fare: float
    sex: str
    """


class PredictResponse(BaseModel):
    prediction: float | int | str
    # TODO(agent): add probability/confidence if the model supports it


@app.get("/health")
def health() -> dict:
    return {{"status": "ok", "model_loaded": "model" in _state}}


@app.post("/predict", response_model=PredictResponse)
def predict(request: PredictRequest) -> PredictResponse:
    if "model" not in _state:
        raise HTTPException(status_code=503, detail="Model not loaded — run training first")
    # TODO(agent): build a feature row from `request` in the exact column order
    # used in training, call _state["model"].predict(...), return the result.
    raise HTTPException(status_code=501, detail="TODO(agent): implement predict")
'''


def _test_pipeline_py() -> str:
    return '''"""Smoke tests for the pipeline — the `test` stage gate.

Run: uv run pytest -q
"""

import pandas as pd
import pytest
from fastapi.testclient import TestClient

from src.config import MODEL_PATH, PROCESSED_DATA


def test_processed_data_exists() -> None:
    assert PROCESSED_DATA.exists(), "Run `uv run python -m src.data_prep` first"
    df = pd.read_parquet(PROCESSED_DATA)
    assert len(df) > 0
    assert df.shape[1] >= 2, "Expected features + target"


def test_model_exists() -> None:
    assert MODEL_PATH.exists(), "Run `uv run python -m src.train` first"


def test_serve_health() -> None:
    from src.serve import app

    with TestClient(app) as client:
        resp = client.get("/health")
        assert resp.status_code == 200


def test_serve_predict() -> None:
    """TODO(agent): fill in a realistic payload for this model's features."""
    from src.serve import app

    payload: dict = {}  # TODO(agent): realistic feature values
    if not payload:
        pytest.skip("TODO(agent): add a realistic /predict payload")
    with TestClient(app) as client:
        resp = client.post("/predict", json=payload)
        assert resp.status_code == 200
        assert "prediction" in resp.json()
'''


def _dockerfile() -> str:
    return """FROM python:3.11-slim

WORKDIR /app
COPY pyproject.toml ./
RUN pip install --no-cache-dir uv && uv pip install --system -r pyproject.toml
COPY src/ src/
COPY models/ models/

EXPOSE 8000
CMD ["uvicorn", "src.serve:app", "--host", "0.0.0.0", "--port", "8000"]
"""


async def scaffold_project_handler(args: dict[str, Any], **_kw) -> tuple[str, bool]:
    project_name = _slugify(args.get("project_name", ""))
    domain = args.get("domain", "tabular")
    if domain not in _DOMAIN_DEPS:
        return f"Unknown domain '{domain}'. Choose one of: {', '.join(_DOMAIN_DEPS)}.", False
    task = args.get("task_description", "")
    parent_dir = args.get("parent_dir") or DEFAULT_PARENT_DIR

    root = Path(parent_dir) / project_name
    if root.exists() and any(root.iterdir()):
        return (
            f"Directory {root} already exists and is not empty. "
            f"Choose a different project_name or delete it first."
        ), False

    files: dict[str, str] = {
        "README.md": _readme(project_name, domain, task),
        "pyproject.toml": _pyproject(project_name, domain),
        ".gitignore": _gitignore(),
        "plan.json": json.dumps(_plan(domain, task), indent=2),
        "src/__init__.py": "",
        "src/config.py": _config_py(domain),
        "src/data_prep.py": _data_prep_py(domain, task),
        "src/train.py": _train_py(domain),
        "src/evaluate.py": _evaluate_py(),
        "src/serve.py": _serve_py(project_name),
        "tests/__init__.py": "",
        "tests/test_pipeline.py": _test_pipeline_py(),
        "Dockerfile": _dockerfile(),
        "data/raw/.gitkeep": "",
        "data/processed/.gitkeep": "",
        "models/.gitkeep": "",
    }

    try:
        for rel_path, content in files.items():
            target = root / rel_path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
    except Exception as e:
        return f"scaffold error: {e}", False

    file_list = "\n".join(f"  {p}" for p in files)
    return (
        f"[scaffold_project DONE] Created MLOps project at {root}\n\n"
        f"Files created:\n{file_list}\n\n"
        f"The project is a complete pipeline skeleton: data prep -> train (MLflow) -> "
        f"evaluate -> tests -> FastAPI serving -> Docker. Structure and boilerplate are "
        f"final — only the sections marked `TODO(agent)` need code.\n\n"
        f"Your next action:\n"
        f"1. Read {root / 'plan.json'} — current stage is `data_prep`\n"
        f"2. Complete ONLY that stage's file ({root / 'src' / 'data_prep.py'}): "
        f"replace each `TODO(agent)` section using the edit tool\n"
        f"3. Run the stage's gate command with bash (work_dir: {root})\n"
        f"4. If the gate passes: update plan.json (set the stage status to 'done', "
        f"advance current_stage) and move to the next stage\n"
        f"Work on ONE stage at a time. Do not touch files from later stages."
    ), True


SCAFFOLD_PROJECT_TOOL_SPEC = {
    "name": "scaffold_project",
    "description": (
        "Create a complete end-to-end MLOps project skeleton on disk: data prep, "
        "training with MLflow tracking, evaluation, pytest smoke tests, FastAPI "
        "serving, Dockerfile, and a plan.json stage tracker with a verification "
        "gate per stage.\n\n"
        "Use this INSTEAD of generate_ml_script when the user asks for a full "
        "project / pipeline / MLOps setup (not a single script). The scaffold is "
        "deterministic — after it runs, complete the `TODO(agent)` sections one "
        "stage at a time following plan.json, verifying each stage with its gate "
        "command before advancing."
    ),
    "parameters": {
        "type": "object",
        "required": ["project_name", "domain"],
        "additionalProperties": False,
        "properties": {
            "project_name": {
                "type": "string",
                "description": "Short kebab-case name, e.g. 'churn-predictor'. Becomes the folder name.",
            },
            "domain": {
                "type": "string",
                "enum": ["tabular", "cv", "nlp", "timeseries", "rl"],
                "description": "ML domain — selects dependencies and domain hints in the templates.",
            },
            "task_description": {
                "type": "string",
                "description": "One-sentence task description, e.g. 'Predict customer churn from usage data'. Embedded in README and TODO context.",
            },
            "parent_dir": {
                "type": "string",
                "description": f"Directory to create the project in. Default: {DEFAULT_PARENT_DIR}",
            },
        },
    },
}
